[project]
name = "codegamers-zorton-brothers"
version = "1.1.0"
authors = [{ name = "havi" }]
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "opencv-python>=4.12.0.88",
    "pyside6>=6.10.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
